name: Dream11 CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Rspec Coverage
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Password123
          MYSQL_DATABASE: dream11
          MYSQL_USER: dream11
          MYSQL_PASSWORD: Password123
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - name: Cache Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-bundler-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-bundler-
      - name: Install dependencies
        run: |
          bundle install --path=vendor/bundle
      - name: Setup Database
        run: |
          cp config/database.yml.ci config/database.yml
          bin/rails db:test:prepare
      - name: Run Rspec
        run: bundle exec rspec
